# Generated by Django 5.0.1 on 2024-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
