# Generated by Django 5.0.1 on 2024-02-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_pay_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
