# Generated by Django 5.0.1 on 2024-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Превью')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(choices=[(True, 'Активен'), (False, 'Неактивен')], default=False, verbose_name='Актуальность')),
                ('public_date', models.DateField(auto_now=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['name', 'public_date'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Превью')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(choices=[(True, 'Активен'), (False, 'Неактивен')], default=False, verbose_name='Актуальность')),
                ('public_date', models.DateField(auto_now=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['name', 'public_date'],
            },
        ),
    ]
