# Generated by Django 5.0.1 on 2024-01-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_price_lesson_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
