# Generated by Django 5.0.1 on 2024-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['public_date', 'course', 'user'], 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_url',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
