# Generated by Django 5.0.1 on 2024-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_payment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сессия для оплаты в Stripe'),
        ),
    ]
