# Generated by Django 5.0.1 on 2024-02-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_payment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_url',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
