# Generated by Django 4.2.10 on 2024-02-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_payment_pay_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='course',
            name='public_date',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
